apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-code-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/server
    server: 172.17.6.50
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
