apiVersion: v1
kind: Service
metadata:
  name: backend-service-clusterip
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: backend-port
    protocol: TCP
    port: 3030
    targetPort: 3030
  - name: backend-https
    protocol: TCP
    port: 443
    targetPort: 443
