apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-code-pv
spec:
  capacity:
    storage: 7700Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nfs/code/FaceBook_Controlling
    server: 172.31.24.178

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-code-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7700Gi
