apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-code-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/code/Twitter_Controlling_Emulator
    server: 192.168.100.134

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/logs
    server: 192.168.100.134
    

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-profile-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/profile
    server: 192.168.100.134

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-code-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-profile-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
