apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: android-service
spec:
  serviceName: "android-service"
  replicas: 2
  selector:
    matchLabels:
      app: android
  template:
    metadata:
      labels:
        app: android
    spec:
      containers:
      - name: android
        image: mohamedzahran1989/android-emulator:v1-head
        ports:
        - containerPort: 4725
          name: appium
        - containerPort: 5900
          name: vnc
        - containerPort: 6080
          name: novnc
        env:
        - name: APPIUM_PORT
          value: "4725"
        - name: HTTP_PROXY
          value: "http://glidersilage:EvaS456789@41.223.53.14:13129"
        - name: HTTPS_PROXY
          value: "http://glidersilage:EvaS456789@41.223.53.14:13129"
        - name: backend_domain
          value: "https://backend-service-clusterip.default.svc.cluster.local:3030"
        - name: containerName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SSL_PORT
          value: "443"
        volumeMounts:
        - name: emulator-code-volume
          mountPath: /usr/local/bin/codes
        - name: emulator-logs-volume
          mountPath: /usr/local/bin/logs
        - name: emulator-profile-volume
          mountPath: /usr/local/bin/actions
        - name: emulator-profile-volume 
          mountPath: /root/.android
        # - name: emulator-profile-volume  
        #   mountPath: /root/.android/avd
        securityContext:
          privileged: true
      volumes:
      - name: emulator-code-volume
        persistentVolumeClaim:
          claimName: emulator-code-pvc
      - name: emulator-logs-volume
        persistentVolumeClaim:
          claimName: emulator-logs-pvc
      - name: emulator-profile-volume
        persistentVolumeClaim:
          claimName: emulator-profile-pvc
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 500
