apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-code-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.7
    path: /mnt/nfs/codes

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.7
    path: /mnt/nfs/logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: emulator-profile-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.7
    path: /mnt/nfs/profile

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-code-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulator-profile-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
