apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: facebook-controlling-statefulset
  labels:
    app: engine
spec:
  serviceName: "engine-clusterip-service"
  replicas: 5
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: engine
        image: mohamedzahran1989/umbra1:v1.1
        ports:
        - containerPort: 80
        env:
        - name: backend_domain
          value: "https://backend-service-clusterip.default.svc.cluster.local:3030"
        - name: containerName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SSL_PORT
          value: "443"
        volumeMounts:
        - name: nfs-code-volume
          mountPath: /usr/local/bin/codes
        - name: logs-volume
          mountPath: /usr/local/bin/logs
        - name: profile-volume
          mountPath: /usr/local/bin/actions
        - name: screenshots-volume
          mountPath: /usr/local/bin/screenshots
      volumes:
      - name: nfs-code-volume
        persistentVolumeClaim:
          claimName: nfs-code-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: profile-volume
        persistentVolumeClaim:
          claimName: profile-pvc
      - name: screenshots-volume
        persistentVolumeClaim:
          claimName: repos-pvc
  podManagementPolicy: "Parallel"  # Correct location for podManagementPolicy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 500  # Set this to the maximum you can afford to have unavailable to increase rollout speed
