apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkedin-statefulset
  labels:
    app: youtube
spec:
  serviceName: "linkedin-clusterip-service"
  replicas: 100
  selector:
    matchLabels:
      app: linkedin
  template:
    metadata:
      labels:
        app: linkedin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: linkedin
        image: mohamedzahran1989/um_br:latest
        ports:
        - containerPort: 80
        env:
        - name: backend_domain
          value: "https://backend-service-clusterip.default.svc.cluster.local:3030"
        - name: containerName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SSL_PORT
          value: "443"
        volumeMounts:
        - name: linkedin-code-volume
          mountPath: /usr/local/bin/codes
        - name: logs-volume
          mountPath: /usr/local/bin/logs
        - name: profile-volume
          mountPath: /usr/local/bin/actions
      volumes:
      - name: linkedin-code-volume
        persistentVolumeClaim:
          claimName: linkedin-code-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: profile-volume
        persistentVolumeClaim:
          claimName: profile-pvc
  podManagementPolicy: "Parallel"  # Correct location for podManagementPolicy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 500  # Set this to the maximum you can afford to have unavailable to increase rollout speed
