apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.0-rc2-jammy
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "2135dac8bc8741f8"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "b7fe42219dcefc4a"
        volumeMounts:
        - name: db-storage
          mountPath: /data/db
      # nodeSelector:
      #   kubernetes.io/hostname: avatars-worker-11
      # tolerations:  # This section is what you add for the toleration
      # - key: "key"
      #   operator: "Equal"
      #   value: "value"
        effect: "NoSchedule"
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
