apiVersion: v1
kind: PersistentVolume
metadata:
  name: nsq-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/nsq
    server: 192.168.100.134
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nsq-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
