apiVersion: v1
kind: Service
metadata:
  name: pdfconverter-service
  labels:
    app: pdfconverter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: pdfconverter
