apiVersion: v1
kind: PersistentVolume
metadata:
  name: repos-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/screenshots
    server: 172.31.24.178
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repos-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
