apiVersion: v1
kind: Service
metadata:
  name: umbra1-sentiment-service
  labels:
    app: umbra1-sentiment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: umbra1-sentiment
