apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/ssl
    server: 172.17.6.50
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
