apiVersion: v1
kind: Service
metadata:
  name: twitter-controlling-clusterip-service
  labels:
    app: twitter-controlling
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: twitter-controlling
