apiVersion: v1
kind: Service
metadata:
  name: youtube-nodeport-service
  labels:
    app: youtube
spec:
  type: NodePort
  selector:
    app: youtube  # Ensure this matches the labels of your StatefulSet pods
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ssl
    port: 443
    targetPort: 443
