apiVersion: v1
kind: Service
metadata:
  name: youtube4-clusterip-service
  labels:
    app: youtube4
spec:
  type: ClusterIP
  selector:
    app: youtube4  # Ensure this matches the labels of your StatefulSet pods
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ssl
    port: 443
    targetPort: 443
