apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: youtube-controlling-statefulset
  labels:
    app: youtube
spec:
  serviceName: "youtube-clusterip-service"
  replicas: 400
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: youtube
        image: mohamedzahran1989/um_co:update
        ports:
        - containerPort: 80
        env:
        - name: backend_domain
          value: "https://backend-service-clusterip.default.svc.cluster.local:3030"
        - name: containerName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SSL_PORT
          value: "443"
        volumeMounts:
        - name: youtube-code-volume
          mountPath: /usr/local/bin/codes
        - name: logs-volume
          mountPath: /usr/local/bin/logs
        - name: profile-volume
          mountPath: /usr/local/bin/actions
        - name: screenshots-volume
          mountPath: /usr/local/bin/repos/Screen_shots
      volumes:
      - name: youtube-code-volume
        persistentVolumeClaim:
          claimName: youtube-code-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: profile-volume
        persistentVolumeClaim:
          claimName: profile-pvc
      - name: screenshots-volume
        persistentVolumeClaim:
          claimName: repos-pvc
  podManagementPolicy: "Parallel"  # Correct location for podManagementPolicy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 500  # Set this to the maximum you can afford to have unavailable to increase rollout speed
