apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-code-pv
spec:
  capacity:
    storage: 7700Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/nfs/code/Youtube_Controlling
    server: 172.31.34.159

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-code-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7700Gi
